env:
  browser: true
  es6: true
  jest: true
  serviceworker: true
extends:
  - 'airbnb'
  - 'plugin:flowtype/recommended'
  - 'plugin:jsx-a11y/strict'
  - 'plugin:jest/recommended'
  - 'plugin:prettier/recommended'
  - 'prettier'
  - 'prettier/react'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2020
  sourceType: module
plugins:
  - react
rules:
  import/no-extraneous-dependencies: off
  import/no-named-as-default: off
  jsx-a11y/anchor-is-valid:
    - error
    - components:
        - Link
      specialLink:
        - to
  react/jsx-filename-extension:
    - warn
    - extensions:
        - .js
        - .jsx
  react/no-direct-mutation-state: error
  react/prop-types: off
  react/require-default-props: off
  function-paren-newline: off
  no-throw-literal: off
  no-use-before-define:
    - error
    - nofunc
  no-useless-computed-key: off
settings:
  import/resolver:
    node:
      paths: 'src'
